function init(self)
	msg.post(".", "acquire_input_focus")
end

function update(self, dt)
end

function on_input(self, action_id, action)
	if action_id == hash("up") then
		print("UP!")
	elseif action_id == hash("down") then
		print("DOWN!")
	elseif action_id == hash("left") then
		print("LEFT!")
	elseif action_id == hash("right") then
		print("RIGHT!")
	elseif action_id == hash("click") and action.pressed then
		print("CLICK!")
	end
end